### ISSUE TITLE
Issue with SSH Connection to venus.astro.umontreal.ca

### ISSUE THREAD

**Issue by Aseman7** [njcuk9999/sossisse#5]
Hello, Thank you for your time and for your outstanding work on this project. 

I have been following the instructions for data reduction of TRAPPIST-1b data as an initial example. However, while executing the code, I encountered a problem connecting to the remote server at venus.astro.umontreal.ca. The connection prompts for a password that I do not possess, which is preventing me from proceeding with my analysis. I would greatly appreciate any guidance you could provide to help resolve this connection issue.
<img width="1512" alt="Screenshot 2024-11-04 at 11 59 49" src="https://github.com/user-attachments/assets/8ccd26f6-326d-4876-9d28-72af3fbb7680">

**Comment by njcuk9999** [comment]
Hi, yes, this version only works internally at the moment. We are working on a public release (currently in the "neil") branch. We hope to have it ready for beta testing as soon as possible.
